language: cpp
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
    - COMPILER_VERSION="CC=gcc-4.9 && CXX=g++-4.9" # Use GCC version 4.9
compiler:
  - gcc
before_install:
  - eval "${COMPILER_VERSION}"
  - wget https://www.nsnam.org/release/ns-allinone-3.29.tar.bz2 -q
  - tar xjf ns-allinone-3.29.tar.bz2
  - git clone --depth=1 https://github.com/gscaparrotti/ns3asy ns-allinone-3.29/ns-3.29/src/ns3asy
script:
  - cd ns-allinone-3.29/ns-3.29/
  - ./waf configure
  - ./waf build