language: cpp
branches:
  only:
    - master
    - develop
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
    - COMPILER_VERSION="CC=gcc-4.9 && CXX=g++-4.9" # Use GCC version 4.9
compiler:
  - gcc
before_install:
  - eval "${COMPILER_VERSION}"
  - git clone --depth=1 https://github.com/nsnam/ns-3-dev-git ns-3-dev
  - git clone --depth=1 https://github.com/gscaparrotti/ns3asy ns-3-dev/src/ns3asy
script:
  - cd ns-3-dev/
  - ./waf configure
  - ./waf build